name: CI Workflow - Docker

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Build the Docker image
      - name: Build Docker Image
        run: docker build -t task-manager:latest .

      # Run the Docker image
      - name: Run Docker Container
        run: docker run --rm -e GITHUB_USER="${{ github.actor }}" task-manager:latest